### PR TITLE
Abstract code in TaskList.jsx

### PR DESCRIPTION
**Pull request by kien-ngo**
https://en.wikipedia.org/wiki/Abstraction_principle_(computer_programming)#:~:text=In%20software%20engineering%20and%20programming,abstractions%20provided%20by%20the%20programming

Always make it a habit to avoid duplicating code. Try to achieve the same thing with less code. You'll see yourself improved in a short time.

Other things:

- `overflowY: 'scroll'` will always show a scrollbar. IMO `overflowY: 'auto'` is better.
- `const style = (index === tasks.length - 1) ? { marginBottom: '3rem' } : {};` works but not the best solution. CSS's `:last-child` is cleaner & does not require JavaScript. => Sometimes HTML & CSS are enough.

### CODE REVIEW

**Comment by kien-ngo** [comment]
Also some industry standards:
Use Prettier to format code
Use TypeScript (not JS)

**Comment by kien-ngo** [comment]
Here's an assignment on reducing duplicated code: Try your best to abstract the code in TaskForm & TaskFormMobile

**Comment by phuc1nguyen** [comment]
Nice tips, I think I'll keep the styles for this one but noted.
I'm working my way to Typescript (will use it in later projects), do people always use Typescript over Javascript?
Thanks!

**Comment by kien-ngo** [comment]
Typescript should definitely be the default setup. Any big project that started with vanilla JS should make the switch to Typescript, otherwise the developers will have a terrible time debugging, testing & maintaining the code.

Also, CRA (create-react-app) should no longer be the industry standard. Look into NextJS and learn about SSG, SSR + IRS.

**Comment by phuc1nguyen** [comment]
One more thing about the todo list, do you know how should I update localStorage, I put localStorage.setItem() right after dispatch() but that does not work since dispatch/setState is an async function.

**Comment by kien-ngo** [comment]
You should give me more context next time but I'm assuming you're talking about the `.setItem()` inside TaskContext.jsx's `handleSubmit()`. In that case a suggestion is to use `useEffect`. Let's remove that line and try the following code:
image

Sorry I'm at work so can't test the code

**Comment by phuc1nguyen** [comment]
No worries, that works btw. I should probably do more with these hooks.

**Pull request merged**
